#! /usr/bin/env bash
# ============================================================================ #
#
# Operate on `compile_commands.json' files.
#
# ---------------------------------------------------------------------------- #

set -eu;
set -o pipefail;

# ---------------------------------------------------------------------------- #

_as_me="ccjs";

_version="0.1.0";

_usage_msg="USAGE: $_as_me [OPTIONS...] COMMAND [CMD-OPTIONS...] [ARGS...]

Operate on \`compile_commands.json' files.
";

#shellcheck disable=SC2140
_help_msg="$_usage_msg

OPTIONS
  -h,--help           Print help message to STDOUT.
  -u,--usage          Print usage message to STDOUT.
  -v,--version        Print version information to STDOUT.

COMMANDS
  add FILE FLAGS      Add entry to \`compile_commands.json'.
  remove FILE         Remove entries from \`compile_commands.json'.
  list                List all entries in \`compile_commands.json'.
  show FILE           Show entry from \`compile_commands.json'.

ENVIRONMENT
  CCJS_OUT            Output file. Default: \`./compile_commands.json'.
  JQ                  Command used as \`jq' executable.
  REALPATH            Command used as \`realpath' executable.
  MKTEMP              Command used as \`mktemp' executable.
";


# ---------------------------------------------------------------------------- #

usage() {
  if [[ "${1:-}" = "-f" ]]; then
    echo "$_help_msg";
  else
    echo "$_usage_msg";
  fi
}


# ---------------------------------------------------------------------------- #

_usage_add_msg="USAGE: $_as_me [OPTIONS...] add [CMD-OPTIONS]... \
FILE OUTPUT DIRECTORY ARGS...

Add entry to \`compile_commands.json'.
";

_help_add_msg="$_usage_add_msg
Replaces existing entry if it exists.

When \`--in-place' is specified, \`compile_commands.json' is modified in-place
instead of being printed to \`STDOUT'.
Existing output file will be backed up by adding a \`~' suffix to its name.

ARGUMENTS
  FILE              The source file to compile ( e.g. \`foo.c' ).
  OUTPUT            The output file ( e.g. \`foo.o' ).
  DIRECTORY         The directory in which to run the compiler.

OPTIONS
  -h,--help         Print help message to STDOUT.
  -u,--usage        Print usage message to STDOUT.
  -i,--in-place     Add entry to \`compile_commands.json' in-place.

ENVIRONMENT
  CCJS_OUT            Output file. Default: \`./compile_commands.json'.
  JQ                  Command used as \`jq' executable.
  REALPATH            Command used as \`realpath' executable.
  MKTEMP              Command used as \`mktemp' executable.
";


# ---------------------------------------------------------------------------- #

usage_add() {
  if [[ "${1:-}" = "-f" ]]; then
    echo "$_help_add_msg";
  else
    echo "$_usage_add_msg";
  fi
}


# ---------------------------------------------------------------------------- #

_usage_remove_msg="USAGE: $_as_me [OPTIONS...] remove [CMD-OPTIONS]... FILE...

Remove entries from \`compile_commands.json'.
";

_help_remove_msg="$_usage_remove_msg
When \`--in-place' is specified, \`compile_commands.json' is modified in-place
instead of being printed to \`STDOUT'.
Existing output file will be backed up by adding a \`~' suffix to its name.

ARGUMENTS
  FILE              Source file(s) to be removed ( e.g. \`foo.c' ).

OPTIONS
  -h,--help         Print help message to STDOUT.
  -u,--usage        Print usage message to STDOUT.
  -i,--in-place     Add entry to \`compile_commands.json' in-place.

ENVIRONMENT
  CCJS_OUT            Output file. Default: \`./compile_commands.json'.
  JQ                  Command used as \`jq' executable.
  REALPATH            Command used as \`realpath' executable.
  MKTEMP              Command used as \`mktemp' executable.
";


# ---------------------------------------------------------------------------- #

usage_remove() {
  if [[ "${1:-}" = "-f" ]]; then
    echo "$_help_remove_msg";
  else
    echo "$_usage_remove_msg";
  fi
}


# ---------------------------------------------------------------------------- #

# @BEGIN_INJECT_UTILS@
: "${JQ:=jq}";
: "${REALPATH:=realpath}";
: "${MKTEMP:=mktemp}";
export JQ REALPATH MKTEMP;
# @END_INJECT_UTILS@

# @BEGIN_INJECT_PATH@
PATH="${PATH:+$PATH:}${BASH_SOURCE[0]%/*}";
if [[ -d "${BASH_SOURCE[0]%/*}/../libexec" ]]; then
  PATH="$PATH:${BASH_SOURCE[0]%/*}/../libexec";
fi
export PATH;
# @END_INJECT_PATH@


# ---------------------------------------------------------------------------- #

_TMP_FILES='';
_TMP_DIRS='';
export _TMP_FILES _TMP_DIRS;

#shellcheck disable=SC2120
mktmp_auto() {
  local _tmp;
  _tmp="$( $MKTEMP "$@"; )";
  case " $* " in
    *\ -d\ *|*\ --directory\ *) export _TMP_DIRS="$_TMP_DIRS:$_tmp"; ;;
    *)                          export _TMP_FILES="$_TMP_FILES:$_tmp"; ;;
  esac
  echo "$_tmp";
}


# ---------------------------------------------------------------------------- #

cleanup() {
  local _tmp_files _tmp_dirs;
  if [[ -n "$_TMP_FILES" ]]; then
    IFS=':' read -ra _tmp_files <<< "$_TMP_FILES";
    rm -f "${_tmp_files[@]}";
  fi
  if [[ -n "$_TMP_DIRS" ]]; then
    IFS=':' read -ra _tmp_dirs <<< "$_TMP_DIRS";
    rm -rf "${_tmp_dirs[@]}";
  fi
}

_es=0;
trap '_es="$?"; cleanup; exit "$_es";' HUP TERM INT QUIT EXIT;


# ---------------------------------------------------------------------------- #

# Set the output file.

set_ccjs_out() {
  if [[ -n "${CCJS_OUT:-}" ]]; then
    CCJS_OUT="$( "$REALPATH" "$CCJS_OUT"; )";
  else
    # Find nearest project root or `compile_commands.json' by searching "up".
    _dir="$PWD";
    while [[ "${_dir:-/}" != "/" ]]; do
      if [[ -f "$_dir/compile_commands.json" ]]; then
        CCJS_OUT="$_dir/compile_commands.json";
        break;
      elif [[ -d "$_dir/.git" ]]; then
        CCJS_OUT="$_dir/compile_commands.json";
        break;
      elif [[ -d "$_dir/.root" ]]; then
        CCJS_OUT="$_dir/compile_commands.json";
        break;
      fi
      _dir="${_dir%/*}";
    done
    : "${CCJS_OUT:=$PWD/compile_commands.json}";
    unset _dir;
    export CCJS_OUT;
  fi
}


# ---------------------------------------------------------------------------- #

ccjs_add() {
  _IN_PLACE='';
  _FILE='';
  _OUTPUT='';
  _DIRECTORY='';

  declare -a _cc_args;
  _cc_args=();

  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      -u|--usage)    usage_add;    exit 0; ;;
      -h|--help)     usage_add -f; exit 0; ;;
      -i|--in-place) _IN_PLACE=:;  ;;
      --) shift; break; ;;
      *)
        if [[ -z "$_FILE" ]]; then
          _FILE="$1";
        elif [[ -z "$_OUTPUT" ]]; then
          _OUTPUT="$1";
        elif [[ -z "$_DIRECTORY" ]]; then
          _DIRECTORY="$1";
        else
          _cc_args+=( "$1" );
        fi
      ;;
    esac
    shift;
  done
  # Add remaining arguments to \`_cc_args'.
  if [[ -n "$*" ]]; then
    _cc_args+=( "$@" );
  fi


  # Get absolute paths.

  case "${CCJS_OUT:=$PWD/compile_commands.json}" in
    /*) :; ;;
    *) CCJS_OUT="$( "$REALPATH" "$CCJS_OUT"; )"; ;;
  esac

  case "$_FILE" in
    "") echo "$_as_me: Missing FILE argument." >&2; usage_add >&2; exit 1; ;;
    /*) :; ;;
    *) _FILE="$( "$REALPATH" -m "$_FILE"; )"; ;;
  esac

  case "${_OUTPUT:=${_FILE%.*}.o}" in
    /*) :; ;;
    *) _OUTPUT="$( "$REALPATH" -m "$_OUTPUT"; )"; ;;
  esac

  case "${_DIRECTORY:=$PWD}" in
    /*) :; ;;
    *) _DIRECTORY="$( "$REALPATH" -m "$_DIRECTORY"; )"; ;;
  esac


  # Create entry

  _ARGS='';
  for _arg in "${_cc_args[@]}"; do
    # Escape double quotes.
    _ARGS="${_ARGS:+$_ARGS, }\"${_arg//\"/\\\"}\"";
  done

  _ENTRY="{
    \"directory\": \"$_DIRECTORY\",
    \"file\": \"$_FILE\",
    \"output\": \"$_OUTPUT\",
    \"arguments\": [$_ARGS]
  }";


  # If there's an existing file add the entry to it, otherwise just make a
  # singleton list with the entry.
  if ! [[ -f "$CCJS_OUT" ]]; then
    # If the file doesn't exist create it.
    if [[ -n "$_IN_PLACE" ]]; then
      echo "[$_ENTRY]"|$JQ > "$CCJS_OUT";
    else
      echo "[$_ENTRY]"|$JQ;
    fi
  else
    TMPFILE="$( mktmp_auto; )";
    _JQ_CMD="[\$_ENTRY] + .|unique_by( .output )";
    if [[ -n "$_IN_PLACE" ]]; then
      # Add the entry to the file, and remove old entry ( if present ).
      $JQ --argjson _ENTRY "$_ENTRY" "$_JQ_CMD" "$CCJS_OUT" > "$TMPFILE";
      # Backup the original file.
      mv "$CCJS_OUT" "$CCJS_OUT~";
      # Overwrite the original file.
      mv "$TMPFILE" "$CCJS_OUT";
    else
      $JQ --argjson _ENTRY "$_ENTRY" "$_JQ_CMD" "$CCJS_OUT";
    fi
  fi
}


# ---------------------------------------------------------------------------- #

ccjs_remove() {
  _IN_PLACE='';
  declare -a _files;
  _files=();

  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      -u|--usage)    usage_remove;    exit 0; ;;
      -h|--help)     usage_remove -f; exit 0; ;;
      -i|--in-place) _IN_PLACE=:;  ;;
      *)             _files+=( "$1" ); ;;
    esac
    shift;
  done


  # Get absolute paths.

  case "${CCJS_OUT:=$PWD/compile_commands.json}" in
    /*) :; ;;
    *) CCJS_OUT="$( "$REALPATH" "$CCJS_OUT"; )"; ;;
  esac

  if [[ -z "${_files[*]}" ]]; then
    echo "$_as_me: no input files were given" >&2;
    usage_remove >&2;
    exit 1;
  fi

  _FILES='';
  for _file in "${_files[@]}"; do
    case "$_file" in
      /*) :; ;;
      *) _file="$( "$REALPATH" -m "$_file"; )"; ;;
    esac
    _FILES="${_FILES:+$_FILES, }\"$_file\"";
  done
  _FILES="[$_FILES]";

  TMPFILE="$( mktmp_auto; )";
  #shellcheck disable=SC2016
  _JQ_CMD='map( select( .file as $FILE|
                        ( $_FILES|index( [$FILE] ) ) == null ) )';
  if [[ -n "$_IN_PLACE" ]]; then
    # Add the entry to the file, and remove old entry ( if present ).
    $JQ --argjson _FILES "$_FILES" "$_JQ_CMD" "$CCJS_OUT" > "$TMPFILE";
    # Backup the original file.
    mv "$CCJS_OUT" "$CCJS_OUT~";
    # Overwrite the original file.
    mv "$TMPFILE" "$CCJS_OUT";
  else
    $JQ --argjson _FILES "$_FILES" "$_JQ_CMD" "$CCJS_OUT";
  fi
}


# ---------------------------------------------------------------------------- #

# Parse "global" options up until the first sub-command name.

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    # Split short options such as `-abc' -> `-a -b -c'
    -[^-]?*)
      _arg="$1";
      declare -a _args;
      _args=();
      shift;
      _i=1;
      while [[ "$_i" -lt "${#_arg}" ]]; do
        _args+=( "-${_arg:$_i:1}" );
        _i="$(( _i + 1 ))";
      done
      set -- "${_args[@]}" "$@";
      unset _arg _args _i;
      continue;
    ;;
    --*=*)
      _arg="$1";
      shift;
      set -- "${_arg%%=*}" "${_arg#*=}" "$@";
      unset _arg;
      continue;
    ;;
    -u|--usage)    usage;    exit 0; ;;
    -h|--help)     usage -f; exit 0; ;;
    -v|--version)  echo "$_version"; exit 0; ;;
    --) shift; break; ;;
    -?|--*)
      {
        printf "%s: Unrecognized option: '%s'. " "$_as_me" "$1";
        echo 'Did you forget to name a sub-command?';
      } >&2;
      usage -f >&2;
      exit 1;
    ;;
    add)
      shift;
      set_ccjs_out;
      ccjs_add "$@";
      exit "$?";
    ;;
    remove)
      shift;
      set_ccjs_out;
      ccjs_remove "$@";
      exit "$?";
    ;;
    *)
      echo "$_as_me: Unexpected argument(s) '$*'" >&2;
      usage -f >&2;
      exit 1;
    ;;
  esac
  shift;
done


# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
